### ISSUE TITLE
AuthInterceptor with axios doesn't redirect to the login page when session is lost

### ISSUE THREAD

**Issue by botenbreuk** [42BV/react-authentication#22]
When using the current version of authInterceptor() as in interceptor of axios it wont redirect to the the login page. This is because the method only checks for the response.status. But in axios this is error.response.status. 

The authInterceptor() needs to be changed so that it can accept both or two sperate methods for when using axios or something else.

**Comment by TimQuist** [comment]
I think in order to maintain the ability to upgrade to newer versions of this library whilst not using axios (but ex. fetch), we should make this format customisable for the developer. Otherwise non-axios projects will be stuck on an older version of this library forever.
